[workspace]
members = [
    "crates/nmixx-core",
    "crates/nmixx-app",
    "crates/nmixx-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["ZHOUHENG"]
rust-version = "1.85"

[workspace.dependencies]
clap = { version = "4.6.6", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serial2 = "0.2.38"
thiserror = "2"
toml = "0.9"
